service: gh-contributions-aggregator

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: go1.x
  region: ap-south-1
  apiGateway:
    shouldStartNameWithService: true

package:
  exclude:
  - ./**
  include:
  - ./bin/**
  - ./data/**

functions:
  aggregate:
    handler: bin/gh-contributions-aggregator
    events:
    - http:
        path: aggregate
        method: get
