name: CI

on: push

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.3'

    - name: Install dependencies
      run: |
        go version
        make deps
        make testdeps


    - name: Build
      run: make build.linux

    - name: Test
      run: make test

    - name: Run Vet & Lint
      run: |
        make vet
        make lint
